Repository necst-telescope/observer, pull requests merged in 2023-11, with the labels that each got.

#66 #60 rel0110
  .github/ISSUE_TEMPLATE/release.md
  Dockerfile
  pyproject.toml
Labels: release

#68 #67 change poetry version
  Dockerfile
  pyproject.toml
Labels: bug, release

#70 #69 delete poetry version
  Dockerfile
  pyproject.toml
Labels: bug, release

#72 # add total power
  observer/server.py
  observer/static/chart.js
  observer/static/index.js
  observer/templates/qlook/index.html
  pyproject.toml
Labels: enhancement, release
