Repository necst-telescope/observer, pull requests merged in 2023-05, with the labels that each got.

#40 #39 modify dockerfile version
  Dockerfile
Labels: bug

#42 #41 change import neclib EnvVarName
  observer/server.py
Labels: bug

#43 #36 rename topic
  observer/server.py
  observer/static/quick-look.js
Labels: enhancement

#45 #44 change version number
  pyproject.toml
Labels: enhancement

#47 #46 change dockerfile to necst:v0.6.3
  Dockerfile
Labels: release

#51 #50 re-release
  pyproject.toml
Labels: release

#55 #54 release
  Dockerfile
  pyproject.toml
Labels: release
