Repository necst-telescope/observer, pull requests merged in 2025-03, with the labels that each got.

#99 #73 org list
  observer/static/quick-look.js
  observer/templates/qlook/index.html
Labels: enhancement

#98 #92 sis 2d
  observer/server.py
  observer/static/chart.js
  observer/static/index.js
  observer/templates/qlook/index.html
Labels: bug, enhancement

#102 release_v1.0.1
  Dockerfile
  pyproject.toml
Labels: release
